import shose1 from "/img/shose1.png";

import shose2 from "/img/shose2.png";
import shose3 from "/img/shose3.png";
import shose4 from "/img/shose4.png";

// export const products = [

//   {
//     id: 1,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 2,
//     label: "HOT",
//     img: shose1,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },

//   {
//     id: 3,
//     label: "HOT",
//     img: shose2,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 4,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 5,
//     label: "HOT",
//     img: shose4,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 6,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 7,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 8,
//     label: "HOT",
//     img: shose1,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 1,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 2,
//     label: "HOT",
//     img: shose1,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },

//   {
//     id: 3,
//     label: "HOT",
//     img: shose2,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 4,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 5,
//     label: "HOT",
//     img: shose4,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 6,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 7,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 8,
//     label: "HOT",
//     img: shose1,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 1,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 2,
//     label: "HOT",
//     img: shose1,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },

//   {
//     id: 3,
//     label: "HOT",
//     img: shose2,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 4,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 5,
//     label: "HOT",
//     img: shose4,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 6,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 7,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 8,
//     label: "HOT",
//     img: shose1,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 1,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 2,
//     label: "HOT",
//     img: shose1,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },

//   {
//     id: 3,
//     label: "HOT",
//     img: shose2,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 4,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 5,
//     label: "HOT",
//     img: shose4,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 6,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 7,
//     label: "HOT",
//     img: shose3,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
//   {
//     id: 8,
//     label: "HOT",
//     img: shose1,
//     name: "Nike Air Max 270 React",
//     rating: "★★★★★",
//     price: 149.99,
//     oldPrice: 249.99,
//     discount: "40% Off",
//   },
// ];

export const products = [
  // --------- SHOES 8 items ---------
  {
    id: 1,
    label: "HOT",
    category: "Shoes",
    img: "https://i.ibb.co/0jqHpnp/blue-sneakers.png",
    name: "Nike Air Max 270 React",
    rating: 5,
    price: 149.99,
    oldPrice: 249.99,
    discount: "40% Off",
  },
  {
    id: 2,
    label: "HOT",
    category: "Shoes",
    img: "https://i.ibb.co/WGv4HnH/white-sneakers.png",
    name: "Adidas Ultraboost 21",
    rating: 4,
    price: 139.99,
    oldPrice: 229.99,
    discount: "39% Off",
  },
  {
    id: 3,
    label: "HOT",
    category: "Shoes",
    img: "https://i.ibb.co/XD6LRcz/red-running-shoe.png",
    name: "Puma Running Shoe",
    rating: 4,
    price: 119.99,
    oldPrice: 199.99,
    discount: "40% Off",
  },
  {
    id: 4,
    label: "HOT",
    category: "Shoes",
    img: "https://i.ibb.co/CwSqYqV/black-sneakers.png",
    name: "Reebok Classic",
    rating: 5,
    price: 129.99,
    oldPrice: 219.99,
    discount: "41% Off",
  },
  {
    id: 5,
    label: "HOT",
    category: "Shoes",
    img: "https://i.ibb.co/3CZc4zM/green-sneakers.png",
    name: "New Balance 574",
    rating: 4,
    price: 119.99,
    oldPrice: 199.99,
    discount: "40% Off",
  },
  {
    id: 6,
    label: "HOT",
    category: "Shoes",
    img: "https://i.ibb.co/5M0sJ8D/pink-sneakers.png",
    name: "Converse Chuck Taylor",
    rating: 3,
    price: 89.99,
    oldPrice: 149.99,
    discount: "40% Off",
  },
  {
    id: 7,
    label: "HOT",
    category: "Shoes",
    img: "https://i.ibb.co/ZmY5R3Y/gray-sneakers.png",
    name: "Skechers Go Walk",
    rating: 4,
    price: 99.99,
    oldPrice: 169.99,
    discount: "41% Off",
  },
  {
    id: 8,
    label: "HOT",
    category: "Shoes",
    img: "https://i.ibb.co/V2h0fZk/brown-sneakers.png",
    name: "Vans Old Skool",
    rating: 4,
    price: 79.99,
    oldPrice: 139.99,
    discount: "43% Off",
  },

  // --------- MOBILES 8 items ---------
  {
    id: 9,
    label: "HOT",
    category: "Mobiles",
    img: "https://i.ibb.co/3hJpZ7v/iphone-13.png",
    name: "iPhone 13 Pro",
    rating: 5,
    price: 999.99,
    oldPrice: 1199.99,
    discount: "17% Off",
  },
  {
    id: 10,
    label: "HOT",
    category: "Mobiles",
    img: "https://i.ibb.co/6bYz9Vg/samsung-s21.png",
    name: "Samsung Galaxy S21",
    rating: 4,
    price: 799.99,
    oldPrice: 999.99,
    discount: "20% Off",
  },
  {
    id: 11,
    label: "HOT",
    category: "Mobiles",
    img: "https://i.ibb.co/4R2qXvC/oneplus-9.png",
    name: "OnePlus 9",
    rating: 4,
    price: 729.99,
    oldPrice: 899.99,
    discount: "19% Off",
  },
  {
    id: 12,
    label: "HOT",
    category: "Mobiles",
    img: "https://i.ibb.co/2t6R0bT/google-pixel-6.png",
    name: "Google Pixel 6",
    rating: 5,
    price: 699.99,
    oldPrice: 899.99,
    discount: "22% Off",
  },
  {
    id: 13,
    label: "HOT",
    category: "Mobiles",
    img: "https://i.ibb.co/bzM3SxJ/xiaomi-mi-11.png",
    name: "Xiaomi Mi 11",
    rating: 4,
    price: 649.99,
    oldPrice: 799.99,
    discount: "19% Off",
  },
  {
    id: 14,
    label: "HOT",
    category: "Mobiles",
    img: "https://i.ibb.co/0jXxXKz/oppo-find-x3.png",
    name: "Oppo Find X3",
    rating: 3,
    price: 599.99,
    oldPrice: 749.99,
    discount: "20% Off",
  },
  {
    id: 15,
    label: "HOT",
    category: "Mobiles",
    img: "https://i.ibb.co/Jk5q5vN/vivo-x60.png",
    name: "Vivo X60",
    rating: 4,
    price: 579.99,
    oldPrice: 699.99,
    discount: "17% Off",
  },
  {
    id: 16,
    label: "HOT",
    category: "Mobiles",
    img: "https://i.ibb.co/mq7gkMP/realme-gt.png",
    name: "Realme GT",
    rating: 4,
    price: 499.99,
    oldPrice: 599.99,
    discount: "17% Off",
  },

  {
    id: 1,
    label: "HOT",
    img: shose3,
    name: "Nike Air Max 270 React",
    rating: 4,
    price: 149.99,
    oldPrice: 249.99,
    discount: "40% Off",
  },
  {
    id: 2,
    label: "HOT",
    img: shose1,
    name: "Nike Air Max 270 React",
    rating: 3,
    price: 149.99,
    oldPrice: 249.99,
    discount: "40% Off",
  },

  {
    id: 3,
    label: "HOT",
    img: shose2,
    name: "Nike Air Max 270 React",
    rating: 5,
    price: 149.99,
    oldPrice: 249.99,
    discount: "40% Off",
  },
  {
    id: 4,
    label: "HOT",
    img: shose3,
    name: "Nike Air Max 270 React",
    rating: 2,
    price: 149.99,
    oldPrice: 249.99,
    discount: "40% Off",
  },
  {
    id: 5,
    label: "HOT",
    img: shose4,
    name: "Nike Air Max 270 React",
    rating: 4,
    price: 149.99,
    oldPrice: 249.99,
    discount: "40% Off",
  },
  {
    id: 6,
    label: "HOT",
    img: shose3,
    name: "Nike Air Max 270 React",
    rating: 5,
    price: 149.99,
    oldPrice: 249.99,
    discount: "40% Off",
  },
  {
    id: 7,
    label: "HOT",
    img: shose3,
    name: "Nike Air Max 270 React",
    rating: 3,
    price: 149.99,
    oldPrice: 249.99,
    discount: "40% Off",
  },
  {
    id: 8,
    label: "HOT",
    img: shose1,
    name: "Nike Air Max 270 React",
    rating: 4,
    price: 149.99,
    oldPrice: 249.99,
    discount: "40% Off",
  },

  // --------- CLOTHING 8 items ---------
  {
    id: 17,
    label: "HOT",
    category: "Clothing",
    img: "https://i.ibb.co/f2tZb0K/denim-jacket.png",
    name: "Denim Jacket",
    rating: 4,
    price: 59.99,
    oldPrice: 99.99,
    discount: "40% Off",
  },
  {
    id: 18,
    label: "HOT",
    category: "Clothing",
    img: "https://i.ibb.co/0jT9vZp/hoodie.png",
    name: "Casual Hoodie",
    rating: 5,
    price: 49.99,
    oldPrice: 79.99,
    discount: "38% Off",
  },
  {
    id: 19,
    label: "HOT",
    category: "Clothing",
    img: "https://i.ibb.co/Y0h1tZ9/t-shirt.png",
    name: "Graphic T-shirt",
    rating: 4,
    price: 19.99,
    oldPrice: 29.99,
    discount: "33% Off",
  },
  {
    id: 20,
    label: "HOT",
    category: "Clothing",
    img: "https://i.ibb.co/0BgR7LX/formal-shirt.png",
    name: "Formal Shirt",
    rating: 4,
    price: 39.99,
    oldPrice: 59.99,
    discount: "33% Off",
  },
  {
    id: 21,
    label: "HOT",
    category: "Clothing",
    img: "https://i.ibb.co/k0J7btb/women-dress.png",
    name: "Women Summer Dress",
    rating: 5,
    price: 69.99,
    oldPrice: 99.99,
    discount: "30% Off",
  },
  {
    id: 22,
    label: "HOT",
    category: "Clothing",
    img: "https://i.ibb.co/9cLzQxY/jeans.png",
    name: "Slim Fit Jeans",
    rating: 4,
    price: 49.99,
    oldPrice: 79.99,
    discount: "37% Off",
  },
  {
    id: 23,
    label: "HOT",
    category: "Clothing",
    img: "https://i.ibb.co/jWmCjqL/women-top.png",
    name: "Women Casual Top",
    rating: 4,
    price: 29.99,
    oldPrice: 49.99,
    discount: "40% Off",
  },
  {
    id: 24,
    label: "HOT",
    category: "Clothing",
    img: "https://i.ibb.co/gmqJbr6/jacket.png",
    name: "Leather Jacket",
    rating: 5,
    price: 99.99,
    oldPrice: 149.99,
    discount: "33% Off",
  },

  // --------- GROCERY 8 items ---------
  {
    id: 25,
    label: "HOT",
    category: "Grocery",
    img: "https://i.ibb.co/7RCvX1f/milk.png",
    name: "Fresh Milk 1L",
    rating: 4,
    price: 2.99,
    oldPrice: 3.99,
    discount: "25% Off",
  },
  {
    id: 26,
    label: "HOT",
    category: "Grocery",
    img: "https://i.ibb.co/tZXzqG5/bread.png",
    name: "Whole Wheat Bread",
    rating: 5,
    price: 1.99,
    oldPrice: 2.49,
    discount: "20% Off",
  },
  {
    id: 27,
    label: "HOT",
    category: "Grocery",
    img: "https://i.ibb.co/zX4BxXg/rice.png",
    name: "Basmati Rice 5kg",
    rating: 4,
    price: 9.99,
    oldPrice: 12.99,
    discount: "23% Off",
  },
  {
    id: 28,
    label: "HOT",
    category: "Grocery",
    img: "https://i.ibb.co/6X7tC2j/eggs.png",
    name: "Farm Fresh Eggs (12)",
    rating: 5,
    price: 3.49,
    oldPrice: 4.49,
    discount: "22% Off",
  },
  {
    id: 29,
    label: "HOT",
    category: "Grocery",
    img: "https://i.ibb.co/ncThN9s/apple.png",
    name: "Red Apples 1kg",
    rating: 4,
    price: 4.99,
    oldPrice: 6.99,
    discount: "29% Off",
  },
  {
    id: 30,
    label: "HOT",
    category: "Grocery",
    img: "https://i.ibb.co/RYdD5Xw/orange.png",
    name: "Juicy Oranges 1kg",
    rating: 4,
    price: 3.99,
    oldPrice: 5.49,
    discount: "27% Off",
  },
  {
    id: 31,
    label: "HOT",
    category: "Grocery",
    img: "https://i.ibb.co/x8tdgdS/potato.png",
    name: "Potatoes 5kg",
    rating: 3,
    price: 5.99,
    oldPrice: 7.99,
    discount: "25% Off",
  },
  {
    id: 32,
    label: "HOT",
    category: "Grocery",
    img: "https://i.ibb.co/Zm1LfKp/tomato.png",
    name: "Fresh Tomatoes 1kg",
    rating: 4,
    price: 2.99,
    oldPrice: 3.99,
    discount: "25% Off",
  },
];
